### ISSUE TITLE
The range in the form on the website doesn't extend to all jokes by default

### ISSUE THREAD

**Issue by c10211** [Sv443/JokeAPI#107]
## Describe the bug
The range selector is restricted to 0-191, however the jokes were recently updated to 207

## Steps to reproduce
Press the down arrow on the range selector

## Expected behaviour
207 should drop to 206

Instead it jumps to 191

## Additional information
 -From https://sv443.net/jokeapi/v2/

**Comment by Sv443** [comment]
Hi, thanks for opening an issue!  
I can't reproduce this. For me the range selector works as expected, both the minimum and maximum values go from 0 to 207 and clicking the down arrow goes from 207 to 206.  
Please make sure you aren't browsing an outdated version from your browser's cache. To clear the cache, try pressing CTRL + F5 or enable the "Disable Cache" checkmark in the dev tools (by pressing F12 and going to the "Network" tab and then reloading the page while the dev tools are active).

**Comment by c10211** [comment]
Refreshing worked, I’ll be damned.

Thanks, and while I have your attention: I love your API. I made an app for an assignment, but I’m so happy with how it turned out that I’m sending it to everyone I know

**Comment by Sv443** [comment]
Aww, thank you very much :)
