### ISSUE TITLE
Get more jokes from 1 call

### ISSUE THREAD

**Issue by ThatCopy** [Sv443/JokeAPI#126]
Get more jokes from one call to the API in an array or a JSON format.

i.e `jokes = j.get_joke(amount=10)`

Looping and appending works but its slower and if you want it in a JSON it's even harder.

**Comment by Sv443** [comment]
Thanks for submitting a feature request!  
I've been thinking about adding this feature, I might do it in v2.2.0

**Comment by Sv443** [comment]
Note for myself: Encode jokes when amount > 5
