### ISSUE TITLE
Joke ID 16 capitalizes "He"

### ISSUE THREAD

**Issue by ThatCopy** [Sv443/JokeAPI#133]
## Describe the bug
In joke ID 16 "He" is capitalized but it's not in capitalized jokes.json

## Steps to reproduce
https://sv443.net/jokeapi/v2/joke/Any?format=txt&idRange=16

## Expected behavior
Get 

> Why did the programmer quit his job? Because he didn't get arrays.

## Screenshots

![image](https://user-images.githubusercontent.com/62877244/87814941-fc18f400-c864-11ea-991a-b5a3f76d9ecd.png)
![image](https://user-images.githubusercontent.com/62877244/87815067-38e4eb00-c865-11ea-847e-fd46731febfb.png)

**Comment by Sv443** [comment]
Thanks! I'll fix it the next time I'm working on JokeAPI

**Comment by Sv443** [comment]
[he](https://www.youtube.com/watch?v=X8avbciUP3c)

**Comment by Sv443** [comment]
Fixed in c9b6047e084df31a68113c52e7b619e74230b83e

**Comment by Sv443** [comment]
nvm I am idiot, gonna fix it again in the next commit
