### ISSUE TITLE
Add new domain "jokeapi.dev" to documentation

### ISSUE THREAD

**Issue by Sv443** [Sv443/JokeAPI#152]
Issue that needs to be resolved beforehand: https://github.com/Sv443/CloudflareDUC/issues/24  
Edit: switched to new DUC: https://github.com/LINKIWI/cloudflare-ddns-client

**Comment by Romvnly-Gaming** [comment]
UPDATES?!?!?!

**Comment by Sv443** [comment]
The issue is updated once there are any news
