### ISSUE TITLE
Explicit tag

### ISSUE THREAD

**Issue by thenamesweretakenalready** [Sv443/JokeAPI#166]
Some of the jokes contain explicit language which isn't necessarily nsfw, so isn't marked as such, but in some situations explicit language isn't usable.

## Describe the solution you'd like
A new tag "Explicit", applied to jokes with explicit language.

**Comment by Sv443** [comment]
That's actually a pretty good idea. I'll try to implement it in [v2.2.2](https://github.com/Sv443/JokeAPI/milestone/13)

**Comment by Sv443** [comment]
Added to v2.2.2 in d059146d8d194da5ca773438d9648fbe9bb74cff
