### ISSUE TITLE
Test endpoint for submitting jokes

### ISSUE THREAD

**Issue by ThatCopy** [Sv443/JokeAPI#187]
## Describe the solution you'd like
A endpoint that is the same as the submit one, but it doesn't save anything to the db, to test the api. It will respond same as the normal endpoint, maybe add a `joke` key.

## Describe alternatives you've considered
I can setup a local JokeAPI server, but that takes time and I can't test the internet connection to the hosted api.

**Comment by Sv443** [comment]
Thanks for your suggestion, I really like it! But I think instead I will add a URL parameter to the `/submit` endpoint to have the API do a dry run of adding a joke
