### ISSUE TITLE
Add a safe mode to the API

### ISSUE THREAD

**Issue by Sv443** [Sv443/JokeAPI#196]
Add a safe mode or something similar that blocks out all even just remotely offensive jokes for applications that really cannot allow any slack in the flagging / categories.  
  
This mode will be opt-in, activated by adding `?safe-mode` (value-less) to the URL parameters.  
Joke objects need to have an additional property `safe` that can be `true` or `false`.  
This value is determined when going through the submission prompt and can't be influenced by the client that sent the submission.

**Comment by Romvnly-Gaming** [comment]
I like this idea

**Comment by Juggernaut9** [comment]
Great idea, I got some hate from sharing a frontend app that uses your api, got kicked from a discord server too lol 🤣
