### ISSUE TITLE
Reporting Joke 79

### ISSUE THREAD

**Issue by Romvnly-Gaming** [Sv443/JokeAPI#220]
## Why the joke should be removed / reflagged / recategorized:
IT'S A RACIST JOKE WITH NO POLITICAL FLAGS AND IT'S NOT IN THE DARK CATEGORY. 👎 

## Alternative to the joke:
Dumpster can jokes.

**Comment by Sv443** [comment]
I don't see how it's racist but I'll try to re-flag it
