### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by mr-piffles** [Sv443/JokeAPI#3]
Hey guys i got a question.
I am using this API with much fun, but sometimes my bot crashes 
because of an error it often throws.

![image](https://user-images.githubusercontent.com/49053928/56616756-69b48100-661e-11e9-848b-e658ee41387c.png)

Sometimes the jokes come through, sometimes it will throw this error. 
There is something wrong with the ID of the joke. 

EDIT: So far it only seems to happen on ID 55

**Comment by Sv443** [comment]
Hi,
I see nothing wrong with joke #55 in particular. It has an escape sequence (`\n`) but that really shouldn't be the issue. It sounds to me as if you are parsing the joke before it is completely done being received. This is important as I am using streams and pipes to send the jokes (to make the API slightly faster).

Could you maybe send me a pastebin link to that whole file so I can take a look at it?

**Comment by Sv443** [comment]
Yeah, after looking into it a bit more this issue seems to be commonly caused by malformatted JSON (see [this](https://stackoverflow.com/a/3594969/8602926) for example).
Make sure you are not ending the request prematurely (that sounds like the most likely cause)

**Comment by Sv443** [comment]
If you will be debugging this again, could you please also check whether the `Content-Type` header is set to `application/json`?

**Comment by mr-piffles** [comment]
I looked over the JSON but so far i could not find anything wrong either. 
But it would not be the first time JSON f-up somewhere in the process. 
I have switched to pushing all arrays up into a sql database, stopped using JSON at this point. 
The jokes i am gathering made the file so big it was easier to handle it with a database haha. 
But thanks for the time buddy ;)

**Comment by Sv443** [comment]
Thank **you** for improving JokeAPI!
:)
