### ISSUE TITLE
New wrapper library: Jokes4J

### ISSUE THREAD

**Issue by the-codeboy** [Sv443/JokeAPI#390]
## Link to the project:

```
https://github.com/the-codeboy/Jokes4J
```

<br><br>

## Link to my personal website / GitHub page (optional):

```
https://github.com/the-codeboy/
```

<br><br>

## Is your project explicit or unsafe for minors to view?

- [ ] **Yes**, it contains explicit material
- [ ] **No**, it doesn't contain explicit material

<br><br>

## Notes:

I started working on a java wrapper for the api today. So far it only supports querying the api, but I might add more features later. I couldn't find a template for adding wrappers, so I used this one.

<br><br>

## Checklist:
- [x] I have added my project's name to the title of this issue
- [x] I have filled out at least the first URL (second one is optional)
- [ ] I have specified whether or not my project is explicit

**Comment by Sv443** [comment]
Hi and thank you very much for making a wrapper! I will make sure to add it to the next update.

**Comment by Sv443** [comment]
Sorry for the long wait but I've added it to the readme and the documentation page now.

**Comment by the-codeboy** [comment]
Great 😂
