### ISSUE TITLE
Joke denied

### ISSUE THREAD

**Issue by PositiveUser** [Sv443/JokeAPI#433]
When I submitted a joke, it showed an alert saying that it has a foreseeable future.

The joke is, "Do programmers hate nature? Perhaps. It has too many bugs!"

**Comment by kerner1000** [comment]
That's funny! Maybe this alert is a joke by itself? :D

**Comment by Sv443** [comment]
The submission of jokes is disabled until version 3.0 is released, sorry for the inconvenience
