### ISSUE TITLE
New Java wrapper: jokeapi-java

### ISSUE THREAD

**Issue by khurozov** [Sv443/JokeAPI#462]
## Link to the project:
```
https://github.com/khurozov/jokeapi-java
```

## Link to my personal website / GitHub page (optional):
```
https://github.com/khurozov
```

## Is your project explicit or unsafe for minors to view?
- [ ] **Yes**, it contains explicit material
- [x] **No**, it doesn't contain explicit material

## Checklist:
- [x] I have added my project's name to the title of this issue
- [x] I have filled out at least the first URL (second one is optional)
- [x] I have specified whether or not my project is explicit

**Comment by Sv443** [comment]
Thanks for making a wrapper library! It has been added to the readme and documentation page now.
