### ISSUE TITLE
New dependent: JokeAPI for Kotlin, Java & Android

### ISSUE THREAD

**Issue by ethauvin** [Sv443/JokeAPI#464]
## Link to the project:

```
https://github.com/ethauvin/jokeapi
```

<br><br>

## Link to my personal website / GitHub page (optional):

```
https://erik.thauvin.net/
```

<br><br>

## Is your project explicit or unsafe for minors to view?

- [ ] **Yes**, it contains explicit material
- [x] **No**, it doesn't contain explicit material

<br><br>

## Notes:

- Feature complete

<br><br>

## Checklist:
- [x] I have added my project's name to the title of this issue
- [x] I have filled out at least the first URL (second one is optional)
- [x] I have specified whether or not my project is explicit

**Comment by Sv443** [comment]
Thank you very much for creating this wrapper library! I've added it to the repo's readme but unfortunately I'm unable to modify the documentation page at the moment, until version 3 of the API gets released.

**Comment by Sv443** [comment]
I was able to modify the documentation page and your wrapper is added now.
