### ISSUE TITLE
Line #1499, joke 136

### ISSUE THREAD

**Issue by ahujaesh** [Sv443/JokeAPI#483]
## The joke's ID:
136

## Why the joke should be edited or removed:
This joke should be flagged differently, because it shouldn't show up in safe mode. I have a project in which I use safe mode and I cannot have things like this showing up on there. Thanks.

## Alternative to the joke:
 N/A

**Comment by Sv443** [comment]
Hi, I'm guessing you mean French joke [#136](https://jokeapi.dev/joke/Any?idRange=136&lang=fr)? Because the English one with that ID is already marked unsafe

**Comment by ahujaesh** [comment]
never mind, I must have read it wrong or something - i was talking about the english one in json

**Comment by Sv443** [comment]
Yeah that one should not be able to be served when `?safe-mode` is set. Make sure the parameter is spelled correctly and if you need a second layer of security you could check the flags and the `safe` property on your end too
