### ISSUE TITLE
"Joke submissions are disabled for the forseeable future"

### ISSUE THREAD

**Issue by hwood-vivup** [Sv443/JokeAPI#488]
If we try to submit a joke, filling in the form, it responds with _"Joke submissions are disabled for the forseeable future"_ only _after_ filling in the form.

## Steps to reproduce
Steps to reproduce the unwanted behavior:
1. Follow the link where the website says _"To submit a new joke, [please click here.](https://jokeapi.dev/#submit)"_
2. Spend a few minutes carefully typing in your wonderfully crafted joke
3. Click "Submit>"
4. You have wasted your time because "Joke submissions are disabled for the forseeable future"

## Expected behavior
The website should not invite you to submit a joke, and should not have a form to fill in. The "submit" section should explain that the submissions are disabled instead of showing a form (deleted it. restore it in the future).

It could also have explanation of _why_ submissions are disabled. The section could then be linked from the README "submissions are disabled" note.

**Comment by Sv443** [comment]
Fair, I probably should've done that a long time ago. It was meant more as a temporary band-aid but stayed for a much longer time.
I'll see about getting it done soon.

**Comment by Sv443** [comment]
It has been done
