### ISSUE TITLE
Uncaught error: TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by ooo27** [Sv443/JokeAPI#6]
https://sv443.net/jokeapi/category/Programming

Gives me:

Uncaught error: TypeError: Cannot read property 'toString' of undefined
If this error persists, please submit an issue here: https://github.com/Sv443/JokeAPI/issues 
Thanks!

- Sv443

**Comment by Sv443** [comment]
Duplicate of #5.
Thanks for submitting though! I will try to fix it ASAP :)
