### ISSUE TITLE
support plaintext return

### ISSUE THREAD

**Issue by intrand** [Sv443/JokeAPI#60]
## Is your feature request related to a problem? Please describe.
Not with your API. [Nightbot](https://docs.nightbot.tv/what-is-nightbot) sucks at parsing JSON when it contains escaped quotes and other special characters.

## Describe the solution you'd like
Return of jokes (single & twopart) on a single plaintext line.

## Describe alternatives you've considered
I could write my own API that calls yours and returns plaintext, but that'd just be a really crappy way to implement something your API could easily directly supply. JSON, YAML and XML are already options.

## Additional context
Feel free to try messing with Nightbot to see if you can get it working cleanly. [eval documentation here](https://docs.nightbot.tv/commands/variables/eval) | [urlfetch documentation here](https://docs.nightbot.tv/commands/variables/urlfetch)

**Comment by Sv443** [comment]
Hi, thanks for submitting an issue!  
What kind of format would you expect? Could you please give me some examples with jokes of type `single` and `twopart`?

**Comment by Sv443** [comment]
I have implemented your feature request by turning the `\n` char into a real line break, so the response looks like this:  
- Type = single:
    > ```"Can I tell you a TCP joke?"
    > "Please tell me a TCP joke."
    > "OK, I'll tell you a TCP joke."```
- Type = twopart:
    > ```How do you generate a random string?
    > 
    > Put a Windows user in front of Vim and tell him to exit.```  
  
Is that okay or do you need me to change something?

**Comment by intrand** [comment]
That's *precisely* what I was hoping for! Thank you very much @Sv443!

I really appreciate how quickly you were able to implement this!

**Comment by Sv443** [comment]
You're welcome, thanks for the feature request :)  
It'll be available in the next version (v2.1.2) which will probably be released within the next few days.  
To get a response in plain text, you use the URL parameter `format=txt`, just like you'd use `format=xml` to get the joke in XML.  
  
Example: `https://sv443.net/jokeapi/v2/joke/Miscellaneous?blacklistFlags=nsfw,racist&format=txt`.  
  
When this issue is closed it means the feature will be available to use.

**Comment by intrand** [comment]
Just want to report back that it's working great! Thank you again :)

**Comment by Sv443** [comment]
@intrand thank you very much for reporting back! I'm glad I could help you :)

**Comment by Sv443** [comment]
Actually it's broken for me, I'll look into that:  
  
![image](https://user-images.githubusercontent.com/38158426/77253875-c3259580-6c5d-11ea-87c4-41299dc71762.png)  
  
URL: https://sv443.net/jokeapi/v2/joke/Miscellaneous?type=txt&blacklistFlags=nsfw,religious,political,sexist,racist&idRange=143
