### ISSUE TITLE
joke about gender & booleans

### ISSUE THREAD

**Issue by Ymx1ZQ** [Sv443/JokeAPI#76]
## The joke's ID
47

## Why the joke should be removed
it should not be removed... it should be just marked as political or sexist or something like this. I know many people within my network who might be offended... right now I am just manually excluding it from the results, but it would be easier to blacklist it!

**Comment by Sv443** [comment]
Hi, thank you for reporting the joke. I will mark it as `sexist`, but it might take a while for it to update since I am currently migrating to another server. As soon as this issue is closed, the change is made public.

**Comment by Sv443** [comment]
It's now implemented, see https://sv443.net/jokeapi/v2/joke/Any?idRange=47
