### ISSUE TITLE
Small typo.

### ISSUE THREAD

**Issue by LiamTownsley** [Sv443/JokeAPI#82]
## Where is the grammar mistake?
Not got a screenshot but it's a 2 part dark joke:
"Why can't orphans play baseball?"
> "hey don't know where home is."

## What is the correct spelling?
"They don't know where home is."

**Comment by Sv443** [comment]
Thank you very much for submitting an issue and a pull request. There's some very minor changes I will need you to make: https://github.com/Sv443/JokeAPI/pull/83/files#r421332149  
Other than that it looks good!
